import { currentYear } from '@/app/common/constants'

export type ProductType = {
  id: number
  name: string
  category: string
  pics: number
  price: number
  status: string
  created_at: string
  image: string
  description: string
}
export const ProductData: ProductType[] = [
  {
    id: 1,
    name: 'Apple Watch',
    category: 'Sports',
    pics: 32,
    price: 39,
    status: 'Published',
    created_at: '14 Jan ' + currentYear + ', 10:30am',
    image: 'assets/images/products/04.png',
    description: 'Size-05 (Model 2021)',
  },
  {
    id: 2,
    name: 'Morden Chair',
    category: 'Interior',
    pics: 10,
    price: 99,
    status: 'Published',
    created_at: '18 Jan ' + currentYear + ', 12:10am',
    image: 'assets/images/products/01.png',
    description: 'Size-Mediam (Model 2021)',
  },
  {
    id: 3,
    name: 'Reebok Shoes',
    category: 'Footwear',
    pics: 24,
    price: 49,
    status: 'Inactive',
    created_at: '24 Jan ' + currentYear + ', 09:10pm',
    image: 'assets/images/products/05.png',
    description: 'size-08 (Model 2021)',
  },
  {
    id: 4,
    name: 'Cosco Vollyboll',
    category: 'Sports',
    pics: 8,
    price: 49,
    status: 'Published',
    created_at: '08 Feb ' + currentYear + ', 03:30pm',
    image: 'assets/images/products/06.png',
    description: 'size-04 (Model 2021)',
  },
  {
    id: 5,
    name: 'Royal Purse',
    category: 'Life Style',
    pics: 52,
    price: 89,
    status: 'Published',
    created_at: '20 Feb ' + currentYear + ', 11:30am',
    image: 'assets/images/products/04.png',
    description: 'Pure Lether 100%',
  },
  {
    id: 6,
    name: 'New Morden Chair',
    category: 'Interior',
    pics: 6,
    price: 20,
    status: 'Draft',
    created_at: '14 Jan ' + currentYear + ', 10:30am',
    image: 'assets/images/products/03.png',
    description: 'size-05 (Model 2021)',
  },
  {
    id: 7,
    name: 'Important Chair',
    category: 'Interior',
    pics: 32,
    price: 39,
    status: 'Published',
    created_at: '02 Mar ' + currentYear + ', 10:30am',
    image: 'assets/images/products/02.png',
    description: 'size-05 (Model 2021)',
  },
  {
    id: 8,
    name: 'Nivya Footboll',
    category: 'Sports',
    pics: 32,
    price: 39,
    status: 'Inactive',
    created_at: '11 Mar ' + currentYear + ', 05:30am',
    image: 'assets/images/products/02.png',
    description: 'Size-05 (Model 2021)',
  },
  {
    id: 9,
    name: 'Green Morden Chair',
    category: 'Interior',
    pics: 10,
    price: 99,
    status: 'Published',
    created_at: '28 Mar ' + currentYear + ', 08:45am',
    image: 'assets/images/products/01.png',
    description: 'Size-Mediam (Model 2021)',
  },
  {
    id: 10,
    name: 'Bata Shoes',
    category: 'Footwear',
    pics: 24,
    price: 49,
    status: 'Draft',
    created_at: '05 Apr ' + currentYear + ', 12:30am',
    image: 'assets/images/products/01.png',
    description: 'size-08 (Model 2021)',
  },
  {
    id: 11,
    name: 'Cosco Vollyboll',
    category: 'Sports',
    pics: 8,
    price: 49,
    status: 'Published',
    created_at: '10 Apr ' + currentYear + ', 10:30am',
    image: 'assets/images/products/06.png',
    description: 'size-04 (Model 2021)',
  },
  {
    id: 12,
    name: 'Royal Purse',
    category: 'Life Style',
    pics: 52,
    price: 89,
    status: 'Published',
    created_at: '20 Apr ' + currentYear + ', 10:30am',
    image: 'assets/images/products/04.png',
    description: 'Pure Lether 100%',
  },
  {
    id: 13,
    name: 'New Morden Chair',
    category: 'Interior',
    pics: 6,
    price: 20,
    status: 'Published',
    created_at: '08 May ' + currentYear + ', 01:30am',
    image: 'assets/images/products/03.png',
    description: 'size-05 (Model 2021)',
  },
]
